apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2023-04-26T02:21:22Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: app-dev
  name: app-dev-service
  namespace: default
  resourceVersion: "1076523"
  uid: b52021a4-9062-4daa-a322-28d02e11b0d2
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.16.5.215
  clusterIPs:
  - 10.16.5.215
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31357
    port: 1337
    protocol: TCP
    targetPort: 1337
  selector:
    app: app-dev
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.133.130.242
