#https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/#:~:text=1%20Deploy%20the%20PV%20and%20PVC%20of%20the,the%20Deployment%3A%20...%205%20Inspect%20the%20PersistentVolumeClaim%3A%20

apiVersion: v1

kind: Service

metadata:

  name: mysql

spec:

  ports:

  - port: 3306

  selector:

    app: mysql

  clusterIP: None

---

apiVersion: apps/v1

kind: Deployment

metadata:

  name: mysql

spec:

  selector:

    matchLabels:

      app: mysql

  strategy:

    type: Recreate

  template:

    metadata:

      labels:

        app: mysql

    spec:

      containers:

      - image: mysql:5.6

        name: mysql

        env:

          # Use secret in real usage

        - name: MYSQL_ROOT_PASSWORD

          value: password

        ports:

        - containerPort: 3306

          name: mysql

        volumeMounts:

        - name: mysql-persistent-storage

          mountPath: /var/lib/mysql

      volumes:

      - name: mysql-persistent-storage

        persistentVolumeClaim:

          claimName: mysql-pv-claim
