services:
  frontend:
    image: jmuniz1985:golang 
    ports:
      - "443:8043"
    networks:
      - front-tier
      - back-tier
#    configs:
#      - httpd-config
#    secrets:
#      - server-certificate

  backend:
    image: jmuniz1985:golang 
#    volumes:
#      - db-data:/etc/data
    networks:
      - back-tier

#volumes:
#  db-data:
#    driver: flocker
#    driver_opts:
#      size: "1GiB"

configs:
  httpd-config:
    external: false

secrets:
  server-certificate:
    external: false
    file: /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

networks:
  # The presence of these objects is sufficient to define them
  front-tier: {}
  back-tier: {}